### ISSUE TITLE
Example code in README not working as expected

### ISSUE THREAD

**Issue by criticalmash** [node-base/base-cwd#1]
Just tried the example for using base-cwd and I immediately ran into issues.

``` js
var cwd = require('base-cwd');
var Base = require('base');
var app = new Base();
app.use(cwd());

console.log(app.cwd);
```

I expect to see a file path, instead I got `undefined`.

After poking around I noticed that the constructor function expects a type value, so I updated my test...

``` js
var cwd = require('base-cwd');
var Base = require('base');
var app = new Base();
app.use(cwd('base'));

console.log(app.cwd);
```

This returns a path as expected.
So, is the documentation wrong, or is it the script?

BTW: I'm looking forward to playing around with base some more.

**Comment by criticalmash** [comment]
After trying out base-data and having similar issues I looked at the tests for data and noticed this line...

``` js
Base.use(function() {
  this.isApp = true;
});
```

which seems to fix the issue as well.

**Comment by jonschlinkert** [comment]
(Sorry I thought I made a comment last night about this, but I just remembered I was having connection issues for a while so I never published the comment)

Most of the existing plugins will require `isApp`. Apologies for not making that clear, we started using that convention after the fact. We do have some docs to push up though, I'll try to do that today. In the meantime, here is a gist with an incomplete version of the docs for "smart plugins": https://gist.github.com/jonschlinkert/f30f1f882feb01ec21dc9a6d8086dbc7.

any feedback would be great

**Comment by criticalmash** [comment]
No problem, if I read enough tests I'll eventually figure it out. I just wanted to help out the next person who reads the docs.

BTW: very impressed with all the code you and @doowb have produced and documented. Don't know where you found the time.
